//  TODO, check for session OR API key
// TODO if no email found, should use login@users.noreply.github.com

import { client } from "@/app/util/octokit";
import { NextResponse } from "next/server";
import yaml from "yaml";

interface File {
  path: string;
  mode: "100644" | "100755" | "040000" | "160000" | "120000";
  type: "commit" | "tree" | "blob";
  sha?: string | null;
  content: string;
}

export async function POST(req: Request) {

  // CREATE PR
  const {
    data: { html_url: url },
  } = await client.pulls.create({
    ...repoConf,
    head,
    base,
    title: "Update YAML",
    body: "This was generated by a bot",
  });

  return NextResponse.json({ url });
}
