import Header from "@/components/header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen justify-center items-center text-center">
          {/* <Header /> */}
          <div className="max-w-xl w-full px-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
