import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";
// @ts-ignore
import commitPlugin from "octokit-commit-multiple-files";
import config, { getRepoConfig } from "@/config";

const octokitOptions = {
  authStrategy: createAppAuth,
  auth: {
    clientId: process.env.GITHUB_CLIENT_ID as string,
    clientSecret: process.env.GITHUB_CLIENT_SECRET as string,
    appId: parseInt(process.env.GITHUB_APP_ID as string),
    installationId: parseInt(process.env.GITHUB_APP_INSTALLATION_ID as string),
    privateKey: process.env.GITHUB_APP_PK as string,
  },
  // auth: token.accessToken // TODO if we want to impersonate user?
};

export async function getRepoData(repo: string) {
  const octokit = new Octokit(octokitOptions);
  const { data } = await octokit.repos.get({ repo, owner: config.owner });
  return data;
}

export async function createPullRequest({
  repo,
  description,
  files,
  type,
}: {
  repo: string;
  type: string;
  description: string;
  files: {
    [key: string]: string;
  };
}) {
  // TODO validation
  // const repoConfig = await getRepoConfig(repo);
  const repoData = await getRepoData(repo);

  const OctokitPlugin = Octokit.plugin(commitPlugin);
  const octokit = new OctokitPlugin(octokitOptions);

  // create a nem
  const branch = `c11r/${type}/${new Date().getTime()}`;
  const message = `Create ${type}: ${description}`;
  // todo get the branch
  // const head = branch
  // TODO validaiton based on config file, don't let people push to any repo obvs...

  await octokit.rest.repos.createOrUpdateFiles({
    repo,
    owner: config.owner,
    branch,
    createBranch: true,
    changes: [
      {
        message,
        files,
      },
    ],
  });

  const {
    data: { html_url: url },
  } = await octokit.pulls.create({
    repo,
    owner: config.owner,
    // TODO make it configurable
    base: repoData.default_branch,
    head: branch,
    title: message,
    body: "This was generated by a bot", // TODO some AI?
  });

  // todo error handling
  return url;
}
